xml_viewer/ftp_client/urls.py
from django.conf.urls import url
from ftp_client import views
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^connect/$', views.connect, name='connect'),
    url(r'^tasks/$', csrf_exempt(views.tasks), name='tasks')
]

xml_viewer/xml_viewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from core.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ftp-client/', include('ftp_client.urls', namespace='ftp_client')),
    url(r'^$', index, name='index'),


]

xml_viewer/ftp_client/models.py
from django.db import models

# Create your models here.

xml_viewer/ftp_client/forms.py
from django import forms


class ConnectionForm(forms.Form):
    host = forms.CharField(label='Host:', widget=forms.TextInput(attrs={'class': 'form-control'}))
    login = forms.CharField(label='Login:', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password:', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    connect_type = forms.CharField(widget=forms.HiddenInput(), initial="connect")

xml_viewer/ftp_client/views.py
import os
import ftplib
import stat
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseForbidden
from ftp_client.forms import ConnectionForm
from json import JSONEncoder


def index(request):
    connection_form = ConnectionForm()
    manager = FtpClientLocalManager()

    return render(request, template_name='ftp_client/index.html', context={
        'connection_form': connection_form,
        'local_dir': manager.get_dir_content(),
        'local_dir_path': manager.get_dir(),
    })


def connect(request):
    if request.META['REQUEST_METHOD'] == 'GET':
        return HttpResponseForbidden('403 Access denied')

    connection_form = ConnectionForm(request.POST)
    manager = FtpClientRemoteManager()

    response = {
        'errors': None,
        'success': False,
        'disconnect': False,
        'remote_dir': None,
        'remote_dir_path': None,
    }

    if request.POST['connect_type'] == 'connect':
        if connection_form.is_valid():
            manager.add_connection(TEST_HOST, TEST_USER, TEST_PASSWD)
            response['remote_dir_content'] = manager.get_dir_content()
            response['remote_dir_path'] = manager.get_connection().pwd()
            response['success'] = True
        else:
            response['errors'] = connection_form.errors

    elif request.POST['connect_type'] == 'disconnect':
        manager.close_connection()
        response['disconnect'] = True

    return HttpResponse(JSONEncoder().encode(response))


def tasks(request):
    if 'task' not in request.POST:
        return HttpResponseForbidden('403 Access denied')

    response = dict()

    if request.POST['type'] == 'remote':
        manager = FtpClientRemoteManager()
    else:
        manager = FtpClientLocalManager()

    if request.POST['task'] == 'change_dir':
        manager.set_dir(request.POST['dir'])
        response['cur_dir'] = manager.get_dir()
    elif request.POST['task'] == 'mkdir':
        manager.mkdir(request.POST['dirname'])
    elif request.POST['task'] == 'rename':
        manager.rename_item(request.POST['item'], request.POST['new_item_name'])
    elif request.POST['task'] == 'chmod':
        manager.chmod_items(request.POST.getlist('items[]'), request.POST['permission'])
    elif request.POST['task'] == 'upload':
        remote_manager = FtpClientRemoteManager()
        if request.POST['type'] == 'remote':
            remote_manager.download_items(FtpClientLocalManager().get_dir(), request.POST.getlist('items[]'))
            response['dir_content'] = FtpClientLocalManager().get_dir_content()
        else:
            remote_manager.upload_items(request.POST.getlist('items[]'))
            response['dir_content'] = remote_manager.get_dir_content()
    elif request.POST['task'] == 'remove':
        manager.remove_items(request.POST.getlist('items[]'))

    if 'dir_content' not in response:
        response['dir_content'] = manager.get_dir_content()

    return HttpResponse(JSONEncoder().encode(response))


def connection_status(func):
    def check_connection(*args, **kwargs):
        try:
            args[0].get_connection().voidcmd("NOOP")
        except IOError:
            args[0].reconnect()
        return func(*args, **kwargs)

    return check_connection


class FtpClientLocalManager(object):
    _dir = None

    def __new__(cls, *args, **kwargs):
        if not hasattr(cls, 'instance'):
            cls.instance = super(FtpClientLocalManager, cls).__new__(cls)
            cls.instance._dir = os.getcwd()
        return cls.instance

    def get_dir(self):
        return self._dir

    def set_dir(self, path):
        self._dir = path
        return True

    def mkdir(self, path):
        dir_full_path = os.path.join(self._dir, path)
        if not os.access(self._dir, os.W_OK) or os.path.exists(dir_full_path):
            return False

        os.mkdir(dir_full_path)
        return True

    def rename_item(self, item_name, new_item_name):
        try:
            os.rename(item_name, os.path.join(self._dir, new_item_name))
        except OSError:
            return False
        return True

    def chmod_items(self, items, permission):
        permission = int(permission, 8)
        for item in items:
            os.chmod(item, permission)
        return True

    def remove_dir(self, dirname):
        items = os.listdir(dirname)
        for item in items:
            item_path = os.path.join(dirname, item)
            if os.path.isfile(item_path):
                os.remove(item_path)
            else:
                self.remove_dir(item_path)
        os.rmdir(dirname)
        return True

    def remove_items(self, items):
        for item in items:
            item_type, item_path = item.split('@')
            if item_type == 'file':
                os.remove(item_path)
            else:
                self.remove_dir(item_path)
        return True

    def get_dir_content(self):
        dir_content = list()
        output = list()

        if os.path.exists(self._dir) and os.path.isdir(self._dir):
            dir_content = os.listdir(self._dir)

        for item in dir_content:
            item_path = os.path.join(self._dir, item)
            item_info = {
                'name': item,
                'info': '',
                'size': os.path.getsize(item_path),
                'perms': oct(stat.S_IMODE(os.stat(item_path).st_mode)),
                'type': '',
                'full_path': item_path,
            }

            if os.path.isdir(item_path):
                item_info['info'] = 'Catalog'
                item_info['type'] = 'catalog'
            else:
                item_ext = os.path.splitext(item_path)
                item_info['info'] = '%s-file' % item_ext[1] if len(item_ext) > 1 and item_ext[1] else 'File'
                item_info['type'] = 'file'

            output.append(item_info)

        output.sort(key=lambda i: i['name'] and i['type'])
        output.insert(0, {
            'name': '..',
            'info': '',
            'size': '',
            'perms': '',
            'type': 'catalog',
            'full_path': os.path.dirname(self._dir),
        })
        return output


class FtpClientRemoteManager(object):
    host = None
    user = None
    password = None
    _connection = None

    def __new__(cls, *args, **kwargs):
        if not hasattr(cls, 'instance'):
            cls.instance = super(FtpClientRemoteManager, cls).__new__(cls)
        return cls.instance

    def add_connection(self, host, user, password):
        self.host = host
        self.user = user
        self.password = password
        self._connection = ftplib.FTP(host, user, password, timeout=5)

        return self._connection

    def close_connection(self):
        self.host = None
        self.user = None
        self.password = None
        self._connection.close()
        self._connection = None

    def reconnect(self):
        self._connection = ftplib.FTP(self.host, self.user, self.password, timeout=5)

    def get_connection(self):
        return self._connection

    def upload_file(self, file_path):
        try:
            self._connection.storbinary("STOR %s" % os.path.basename(file_path), open(file_path, 'rb'))
        except ftplib.Error:
            return False
        return True

    def remove_dir(self, dirname):
        self._connection.cwd(dirname)
        dir_content = list()

        try:
            self._connection.retrlines('MLSD', dir_content.append)
        except ftplib.Error:
            return False

        for line in dir_content:
            items = line.split(';')
            item_name = items[-1].strip()
            item_type = items[0].split('=')[1]

            if item_name in ['.', '..']:
                continue

            if item_type == 'dir':
                self.remove_dir(item_name)
            elif item_type == 'file':
                try:
                    self._connection.delete(item_name)
                except ftplib.Error:
                    return False

        try:
            self._connection.cwd('..')
            self._connection.rmd(dirname)
        except ftplib.Error:
            return False
        return True

    @connection_status
    def get_dir(self):
        return self._connection.pwd()

    @connection_status
    def set_dir(self, path):
        try:
            self._connection.cwd(path)
        except ftplib.Error:
            return False
        return True

    @connection_status
    def get_dir_content(self):
        dir_content = list()
        output = list()

        try:
            self._connection.retrlines('MLSD', dir_content.append)
        except ftplib.Error:
            pass

        for line in dir_content:
            items = line.split(';')

            if items[-1].strip() == '.':
                continue

            items[-1] = 'filename=%s' % items[-1].strip()
            items = dict(map(lambda s: s.split('='), items))

            item_info = {
                'name': items['filename'].strip(),
                'info': '',
                'size': items['sizd'] if 'sizd' in items else items['size'],
                'perms': items['UNIX.mode'],
                'type': items['type'],
                'full_path': None
            }

            if items['filename'] in ['.', '..']:
                item_info['full_path'] = os.path.dirname(self._connection.pwd())
                item_info['type'] = 'catalog'
                item_info['size'] = ''
                item_info['perms'] = ''
            else:
                item_info['full_path'] = os.path.join(self._connection.pwd(), items['filename'])

                if items['type'] == 'dir':
                    item_info['info'] = 'Catalog'
                    item_info['type'] = 'catalog'
                else:
                    item_ext = os.path.splitext(items['filename'])
                    item_info['info'] = '%s-file' % item_ext[1] if len(item_ext) > 1 and item_ext[1] else 'File'

xml_viewer/ftp_client/templates/ftp_client/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FTP client</title>
    <link rel="stylesheet" type="text/css" href="{% static 'ftp_client/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ftp_client/css/style.css' %}">
    <script type="text/javascript" src="{% static 'ftp_client/js/jquery-1.11.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'ftp_client/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'ftp_client/js/main.js' %}"></script>
</head>
<body>
<div class="container-fluid">
    <div class="page-header">
        <h1>FTP client</h1>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">Connection settings</div>
        <div class="panel-body">
            <form class="form-inline" method="post" id="connection-form" action="{% url 'ftp_client:connect' %}">
                {% csrf_token %}
                {% for field in connection_form %}
                    {% if field.is_hidden %}
                        {{ field }}
                    {% else %}
                        <div class="form-group">
                            {{ field.errors }}
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-default">Connect</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 dirs-column local" data-type="local">
            <div class="alerts">
                <div class="alert alert-danger" role="alert">
                    <button class="close" aria-label="Close">
                        <span>&times;</span>
                    </button>
                    <strong></strong>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">
                    Local directory: <span class="directory">{{ local_dir_path }}</span>
                    <div class="tasks pull-right">
                        <a class="mkdir" href="#" title="Create folder">
                            <span class="glyphicon glyphicon-folder-open"></span>
                        </a>
                        <a class="rename" href="#" title="rename">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <a class="chmod" href="#" title="change permissions">
                            <span class="glyphicon glyphicon-cog"></span>
                        </a>
                        <a class="upload" href="#" title="Upload to server">
                            <span class="glyphicon glyphicon-upload"></span>
                        </a>
                        <a class="remove" href="#" title="Remove">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                        <div class="tasks-disable"></div>
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-hover">
                        <tr>
                            <th>File name</th>
                            <th>Size</th>
                            <th>Type</th>
                            <th>Permission</th>
                        </tr>
                        {% for item in local_dir %}
                            <tr data-type="{{ item.type }}" data-full-path="{{ item.full_path }}">
                                <td>
                                    {% if item.type == 'catalog' %}
                                        <span class="glyphicon glyphicon-folder-close"></span>
                                    {% else %}
                                        <span class="glyphicon glyphicon-file"></span>
                                    {% endif %}&nbsp;&nbsp;{{ item.name }}
                                </td>
                                <td>{{ item.size }}</td>
                                <td>{{ item.info }}</td>
                                <td>{{ item.perms }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                    <div class="progress-wrapper">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped active" role="progressbar"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 dirs-column remote" data-type="remote">
            <div class="alerts">
                <div class="alert alert-danger" role="alert">
                    <button class="close" aria-label="Close">
                        <span >&times;</span>
                    </button>
                    <strong></strong>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">
                    Remote directory: <span class="directory"></span>
                    <div class="tasks pull-right">
                        <a class="mkdir" href="#" title="Create folder">
                            <span class="glyphicon glyphicon-folder-open"></span>
                        </a>
                        <a class="rename" href="#" title="rename">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <a class="chmod" href="#" title="change permissions">
                            <span class="glyphicon glyphicon-cog"></span>
                        </a>
                        <a class="upload" href="#" title="Download from server">
                            <span class="glyphicon glyphicon-download-alt"></span>
                        </a>
                        <a class="remove" href="#" title="Remove">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                        <div class="tasks-disable"></div>
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-hover">
                        <tr>
                            <th>File name</th>
                            <th>Size</th>
                            <th>Type</th>
                            <th>Permission</th>
                        </tr>
                    </table>
                    <div class="progress-wrapper">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped active" role="progressbar"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-mkdir" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form-inline" id="tasks-mkdir" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Create folder</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="tasks-mkdir-name">New folder name:</label>
                        <input type="text" name="tasks-mkdir-name" id="tasks-mkdir-name" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" value="Create folder" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-rename" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form-inline" id="tasks-rename" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Rename</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="tasks-rename-name">New name:</label>
                        <input type="text" name="tasks-rename-name" id="tasks-rename-name" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" value="Rename" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-chmod" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form-inline" id="tasks-chmod" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Change permission</h4>
                </div>
                <div class="modal-body">
                    <table class="table table-bordered">
                        <tr>
                            <td></td>
                            <td>Read</td>
                            <td>Write</td>
                            <td>Execute</td>
                        </tr>
                        <tr>
                            <td>Owner</td>
                            <td><input type="checkbox" name="owner" value="4"></td>
                            <td><input type="checkbox" name="owner" value="2"></td>
                            <td><input type="checkbox" name="owner" value="1"></td>
                        </tr>
                        <tr>
                            <td>Group</td>
                            <td><input type="checkbox" name="group" value="4"></td>
                            <td><input type="checkbox" name="group" value="2"></td>
                            <td><input type="checkbox" name="group" value="1"></td>
                        </tr>
                        <tr>
                            <td>Other</td>
                            <td><input type="checkbox" name="other" value="4"></td>
                            <td><input type="checkbox" name="other" value="2"></td>
                            <td><input type="checkbox" name="other" value="1"></td>
                        </tr>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" value="Change" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>